#!/usr/bin/env python3
"""Run regression tests against test-prompts.json.

Validates that each test case has required fields and produces a
TEST_REPORT.md summary.

Usage:
    python scripts/run_regression.py
    python scripts/run_regression.py --output TEST_REPORT.md
"""

import json
import sys
import os
from datetime import datetime, timezone

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)
TEST_PROMPTS_PATH = os.path.join(ROOT, "test-prompts.json")
DEFAULT_OUTPUT = os.path.join(ROOT, "TEST_REPORT.md")

REQUIRED_FIELDS = ["id", "prompt", "expected", "assertions", "forbidden"]


def validate_entry(entry: dict, idx: int) -> list[str]:
    """Validate a single test prompt entry."""
    errors = []
    for field in REQUIRED_FIELDS:
        if field not in entry:
            errors.append(f"  Entry #{idx} ({entry.get('id', '?')}): missing '{field}'")
    if "assertions" in entry and not isinstance(entry["assertions"], list):
        errors.append(f"  Entry #{idx} ({entry.get('id', '?')}): 'assertions' must be a list")
    if "forbidden" in entry and not isinstance(entry["forbidden"], list):
        errors.append(f"  Entry #{idx} ({entry.get('id', '?')}): 'forbidden' must be a list")
    if "assertions" in entry and len(entry["assertions"]) == 0:
        errors.append(f"  Entry #{idx} ({entry.get('id', '?')}): 'assertions' is empty")
    return errors


def run_tests(data: list[dict]) -> tuple[list[dict], list[str]]:
    """Run all validation checks. Returns (passed_entries, all_errors)."""
    all_errors = []
    passed = []

    # Check for duplicate IDs
    ids = [e.get("id", "") for e in data]
    seen = set()
    for i, eid in enumerate(ids):
        if eid in seen:
            all_errors.append(f"  Duplicate ID: '{eid}' at index {i}")
        seen.add(eid)

    for i, entry in enumerate(data):
        errors = validate_entry(entry, i)
        if errors:
            all_errors.extend(errors)
        else:
            passed.append(entry)

    return passed, all_errors


def generate_report(data: list[dict], passed: list[dict], errors: list[str], output_path: str):
    """Generate TEST_REPORT.md."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total = len(data)
    pass_count = len(passed)
    fail_count = total - pass_count
    pass_rate = (pass_count / total * 100) if total > 0 else 0

    # Count unique patterns covered
    patterns_covered = set()
    for entry in passed:
        eid = entry.get("id", "")
        # Extract pattern name from ID (e.g., "evolution-gate-required" → "evolution-gate")
        parts = eid.rsplit("-", 1)
        if len(parts) >= 2:
            patterns_covered.add(parts[0])
        else:
            patterns_covered.add(eid)

    lines = [
        "# Regression Test Report",
        "",
        f"**Generated**: {now}",
        f"**Source**: `test-prompts.json` ({total} test cases)",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total test cases | {total} |",
        f"| Passed | {pass_count} |",
        f"| Failed | {fail_count} |",
        f"| Pass rate | {pass_rate:.0f}% |",
        f"| Patterns covered | {len(patterns_covered)} |",
        "",
    ]

    # Results table
    lines.append("## Results")
    lines.append("")
    lines.append("| # | ID | Status | Assertions | Forbidden Checks |")
    lines.append("|---|:---|:------:|:---:|:---:|")

    for i, entry in enumerate(data):
        entry_errors = validate_entry(entry, i)
        status = "✅ PASS" if not entry_errors else "❌ FAIL"
        assertions_count = len(entry.get("assertions", []))
        forbidden_count = len(entry.get("forbidden", []))
        lines.append(f"| {i+1} | `{entry.get('id', '?')}` | {status} | {assertions_count} | {forbidden_count} |")

    if errors:
        lines.append("")
        lines.append("## Errors")
        lines.append("")
        for err in errors:
            lines.append(f"- {err}")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("> This report is auto-generated by `scripts/run_regression.py`.")
    lines.append("> Run `python scripts/run_regression.py` to regenerate.")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return pass_count, fail_count


def main():
    output_path = DEFAULT_OUTPUT
    if "--output" in sys.argv:
        idx = sys.argv.index("--output")
        if idx + 1 < len(sys.argv):
            output_path = sys.argv[idx + 1]

    if not os.path.exists(TEST_PROMPTS_PATH):
        print(f"ERROR: {TEST_PROMPTS_PATH} not found")
        sys.exit(1)

    with open(TEST_PROMPTS_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    print(f"Loaded {len(data)} test cases from test-prompts.json")

    passed, errors = run_tests(data)

    if errors:
        print(f"\n❌ ERRORS ({len(errors)}):")
        for err in errors:
            print(err)

    pass_count, fail_count = generate_report(data, passed, errors, output_path)

    print(f"\n{'='*50}")
    print(f"  PASSED: {pass_count}/{len(data)}")
    print(f"  FAILED: {fail_count}/{len(data)}")
    print(f"  Report: {output_path}")
    print(f"{'='*50}")

    sys.exit(1 if fail_count > 0 else 0)


if __name__ == "__main__":
    main()
